FROM mcr.microsoft.com/azure-functions/python:3.0-python3.9

WORKDIR /app

COPY ./api/requirements.txt ./api/app.py ./api/.flaskenv ./
RUN pip install -r requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]
