version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: teamenigmaacr.azurecr.io/flask:api

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: teamenigmaacr.azurecr.io/flask:client
